### PR TITLE
Fixed updation of 'views'

### PR DESCRIPTION
**Pull request by Ksathwik03**
Issue: 68

#### Short description of what this resolves:
Improve server-side processing of 'likes' and 'views

#### Changes proposed in this pull request and/or Screenshots of changes:
- views update only when different users sees them

### CODE REVIEW

**Comment by Mitul16** [comment]
@Ksathwik03 Well, I was expecting more. Improvements in database accesses :sweat_smile:
Thank you for your efforts, I am merging your contribution :smile:

**Comment by Ksathwik03** [comment]
> @Ksathwik03 Well, I was expecting more. Improvements in database accesses 😅 Thank you for your efforts, I am merging your contribution 😄

Improvements in data base ?? can u elaborate  i will try my best.

**Comment by Ksathwik03** [comment]
> **There is a bit of problem**
> 
> On the frontend, the way views are shown conflicts with your changes. We are using `views + 1` on the frontend, as a view will be added once the image loads.
> 
> So, what we can do is modify the `/api/image/info/<id>` API endpoint to update the views _given a flag was sent_ from the JavaScript on the client-side.
> 
> I am keeping this PR as a draft for now. Please fix that issue as well that will be introduced with your changes.

This is fixed

**Comment by Ksathwik03** [comment]
No views will not be incremented if the person is not logged in but he can see all the public imanges since they are posted to everyome

**Pull request merged**
